init
gitpetr/flashcards pull request #14
Opened 2017-02-26 08:29 UTC by gitpetr

2017-02-26 11:42 UTC, davetoxa commented
@gitpetr Как насчёт тестов?

2017-02-26 11:42 UTC, davetoxa commented on app/controllers/home_controller.rb
> +      @packs = current_user.packs || nil
@gitpetr как насчёт того, чтобы убрать везде || nil ?

2017-02-26 11:42 UTC, davetoxa commented on app/controllers/home_controller.rb
> +      @card.update_attributes(counter_review: 0 )
@gitpetr ох ё.. должен быть вызов 1 метода модели, который делает 1 SQL запрос на обновление, а не 3

2017-02-26 11:42 UTC, davetoxa commented on app/models/card.rb
> +      when 1 then Time.now + 43200
@gitpetr что за 43_200 ? )
плюс ещё нужно прислушаться к hound 
А ешё можно попробовать использовать массив как основу – у него ведь тоже есть индексы с 0 до x

2017-02-26 14:06 UTC, gitpetr commented on app/controllers/home_controller.rb
> +      @card.update_attributes(counter_review: 0 )
чо Ё? Я впервые такое делаю. Копипастил не всегда понимая, а сам впервые.

2017-02-26 19:32 UTC, davetoxa commented on app/controllers/home_controller.rb
> +        : @card.update_attributes(counter_review: @card.counter_review += 1)
@gitpetr вся логика в модели должна быть, а тут только вызов метода модели

2017-02-27 07:08 UTC, davetoxa commented on app/models/card.rb
> +  end
@gitpetr if/else лучше использовать, 
вместо `self.update_attributes` - `update()`

2017-02-27 07:18 UTC, davetoxa requested changes

2017-02-27 07:18 UTC, davetoxa commented on app/models/card.rb
> +    self.review = -3.days.from_now
@gitpetr почему -3? мы же хотим, чтобы карточка появлялась через 3 дня после создания

2017-02-27 07:18 UTC, davetoxa commented on spec/factories/card.rb
> +    counter_review 0
@gitpetr default значения лучше сделать на уровне базы данных

2017-02-27 07:18 UTC, davetoxa commented on spec/models/card_complex_logic_spec.rb
> +    let(:card){ create(:card, original: "Стол", translated: "Table", user: user) }
@gitpetr создание user здесь не требуется, это будет под капотом

2017-02-27 07:18 UTC, davetoxa commented on spec/models/card_complex_logic_spec.rb
> +    end
@gitpetr 1 проверка – 1 тест 
либо метопрограммирование задействовать

2017-02-27 07:18 UTC, davetoxa commented on spec/models/card_complex_logic_spec.rb
> +  describe do
@gitpetr каждому блоку требуется давать описание, чтобы было понятно, что тут происходит

2017-02-27 07:18 UTC, davetoxa commented on app/models/card.rb
> +  def update_term_counter_date_review
@gitpetr лучше методы назвать так:
right_answer!
wrong_answer!

2017-02-27 07:30 UTC, gitpetr commented on spec/factories/card.rb
> +    counter_review 0
на уровне бызы дефолт есть, не создавалось. я думал из-за этого, сейчас удалю

2017-02-27 11:39 UTC, davetoxa commented on app/models/card.rb
> +    end
@gitpetr всместо self.update_attributes -> update()

2017-02-27 11:39 UTC, davetoxa commented on spec/models/card_complex_logic_spec.rb
> +        card.right_answer!
@gitpetr `card.right_answer!` – можно вынести в before

2017-02-27 11:40 UTC, davetoxa commented on spec/models/card_complex_logic_spec.rb
> +        card = create(:card, original: "barrel", translated: "бочка", user: user, term_review: 2)
@gitpetr можно сократить запись создания объекта и переопределить только нужные методы:
`create(:card, term_review: 2)`

2017-02-27 11:40 UTC, davetoxa commented on spec/models/card_complex_logic_spec.rb
> +      card.right_answer!
@gitpetr в before

2017-02-27 11:41 UTC, davetoxa commented on spec/models/card_complex_logic_spec.rb
>      let!(:user){ create(:user, email: 'test', password: 'test', password_confirmation: 'test') }
@gitpetr user? можно опустить

2017-02-27 12:26 UTC, gitpetr commented on spec/models/card_complex_logic_spec.rb
> +        card = create(:card, original: "barrel", translated: "бочка", user: user, term_review: 2)
user: user оставил, иначе ошибка: емаил уже есть

2017-02-27 12:27 UTC, gitpetr commented on spec/models/card_complex_logic_spec.rb
>      let!(:user){ create(:user, email: 'test', password: 'test', password_confirmation: 'test') }
опустил

2017-02-27 13:37 UTC, davetoxa commented on spec/features/image_cards_spec.rb
> +  let!(:user) { create(:user, email: 'test@test.com', password: 'test', password_confirmation: 'test') }
@gitpetr password: 'test', password_confirmation: 'test' – можно опустить, т.к. это значения по умолчанию

2017-02-27 13:37 UTC, davetoxa approved these changes

2017-02-27 13:53 UTC, merged

2017-02-27 13:59 UTC, gitpetr commented on spec/features/image_cards_spec.rb
> +  let!(:user) { create(:user, email: 'test@test.com', password: 'test', password_confirmation: 'test') }
это я добавил, потому как login не проходит
по умолчанию сейчас: sequence(:email) { |n| "person#{n}@example.com" }

2017-02-27 14:03 UTC, gitpetr commented on spec/features/image_cards_spec.rb
> +  let!(:user) { create(:user, email: 'test@test.com', password: 'test', password_confirmation: 'test') }
аа, невнимательно посмотрел

2017-02-27 14:06 UTC, davetoxa commented on spec/features/image_cards_spec.rb
> +  let!(:user) { create(:user, email: 'test@test.com', password: 'test', password_confirmation: 'test') }
😉