first tests commit
gitpetr/flashcards pull request #7
Opened 2017-02-16 16:20 UTC by gitpetr

2017-02-16 17:06 UTC, davetoxa requested changes

2017-02-16 17:06 UTC, davetoxa commented on app/controllers/home_controller.rb
> +      i_am_guessing
Разве работает этот код? Метод же в модели находится. Плюс нужно назвать так, чтобы было понятно что делает метод

2017-02-16 17:06 UTC, davetoxa commented on app/models/card.rb
> +    self.original == txt
Как насчёт кириллицы и заглавных букв? Нужно сделать чтобы проверка была честной

2017-02-16 17:06 UTC, davetoxa commented on spec/models/card_spec.rb
> +  #   expect(card7).not_to be true
Все старое лучше удалить, чтобы не мешалось и не засоряло

2017-02-16 18:05 UTC, gitpetr commented on spec/models/card_spec.rb
> +  #   expect(card7).not_to be true
я подсматриваю пока

2017-02-17 09:16 UTC, davetoxa commented on spec/models/card_spec.rb
> +    expect(Card.new(original: "Дом", translated: "дом")).to be_valid
Почему валидная карточка? Одно и тоже ведь

2017-02-17 15:16 UTC, merged